apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: nv5d2pz99-python
  janus-idp.io/tekton: nv5d2pz99-python
  backstage.io/kubernetes-id: nv5d2pz99-python
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: nv5d2pz99-python
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
