apiVersion: route.openshift.io/v1
kind: Route
metadata: 
  labels: 
    app.kubernetes.io/instance: nv5d2pz99-python
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: nv5d2pz99-python 
  name: nv5d2pz99-python
spec:
  port:
    targetPort: 8081 
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: nv5d2pz99-python
    weight: 100 
